/* Pasta direcionada a criação de novos livros */
const data = {
  produtos: [
    {
      name: 'Game of Thrones',
      /* slug o que você verá na url será utilizado como único */
      slug: 'livro-game-of-thornes',
      categoria: 'medieval',
      image: '/dados/gameof.jpg',
      preco: 49.99,
      contagem: 10,
      nota: 5.0,
      avaliacoes: 12,
      autor: 'George R. R. Martin',
    },
    {
      name: 'A arte da guerra',
      slug: 'livro-arte-da-guerra',
      categoria: 'medieval',
      image: '/dados/arteDaGuerra.jpg',
      preco: 14.49,
      contagem: 14,
      nota: 4.2,
      avaliacoes: 5,
      autor: 'Sun Tzu',
    },
    {
      name: 'O Príncipe',
      slug: 'livro-o-principe',
      categoria: 'Classicos',
      image: '/dados/oPrincipe.jpg',
      preco: 21.59,
      contagem: 4,
      nota: 54.6,
      avaliacoes: 18,
      autor: 'Maquiavel',
    },
    {
      name: ' Pequeno Manual Antirracista',
      slug: 'livro-manual-antirracista',
      categoria: 'Educação',
      image: '/dados/manual_anti_racismo.jpg',
      preco: 24.4,
      contagem: 9,
      nota: 5.0,
      avaliacoes: 18,
      autor: 'Djamila Ribeiro',
    },
    {
      name: ' Os Condenados da Terra',
      slug: 'livro-condenados-da-terra',
      categoria: 'Educação',
      image: '/dados/os_condenados.jpg',
      preco: 47.59,
      contagem: 10,
      nota: 4.1,
      avaliacoes: 12,
      autor: 'Frantz Fanon',
    },
    {
      name: ' É Assim que Acaba',
      slug: 'livro-assim-que-acaba',
      categoria: 'Educação',
      image: '/dados/assim_que_acaba.jpg',
      preco: 38.59,
      contagem: 10,
      nota: 3.9,
      avaliacoes: 12,
      autor: 'Colleen Hoover',
    },
    {
      name: 'Hamlet',
      slug: 'livro-hamlet',
      categoria: 'Dramaturgia',
      image: '/dados/hamlet.jpg',
      preco: 9.45,
      contagem: 10,
      nota: 3.8,
      avaliacoes: 6,
      autor: 'William Shakespeare',
    },
  ],
};

/* exportar os dados para outros repositórios */
export default data;
