/* Pasta direcionada a criação de novos livros */
const data = {
  produtos: [
    {
      name: 'Game of Thrones',
      /* slug o que você verá na url será utilizado como único */
      slug: 'livro-game-of-thornes',
      categoria: 'medieval',
      image: '/dados/gameof.jpg',
      preco: 49.99,
      contagem: 10,
      nota: 5.0,
      avaliacoes: 12,
      autor: 'George R. R. Martin',
    },
    {
      name: 'A arte da guerra',
      slug: 'livro-arte-da-guerra',
      categoria: 'medieval',
      image: '/dados/arteDaGuerra.jpg',
      preco: 14.49,
      contagem: 14,
      nota: 4.2,
      avaliacoes: 5,
      autor: 'Sun Tzu',
    },
    {
      name: 'O Príncipe',
      slug: 'livro-o-principe',
      categoria: 'Classicos',
      image: '/dados/oPrincipe.jpg',
      preco: 21.59,
      contagem: 4,
      nota: 4.0,
      avaliacoes: 18,
      autor: 'Maquiavel',
    },
    {
      name: ' Pequeno Manual Antirracista',
      slug: 'livro-manual-antirracista',
      categoria: 'Educação',
      image: '/dados/manual_anti_racismo.jpg',
      preco: 24.4,
      contagem: 9,
      nota: 5.0,
      avaliacoes: 18,
      autor: 'Djamila Ribeiro',
    },
    {
      name: ' Os Condenados da Terra',
      slug: 'livro-condenados-da-terra',
      categoria: 'Educação',
      image: '/dados/os_condenados.jpg',
      preco: 47.59,
      contagem: 10,
      nota: 4.1,
      avaliacoes: 12,
      autor: 'Frantz Fanon',
    },
    {
      name: ' É Assim que Acaba',
      slug: 'livro-assim-que-acaba',
      categoria: 'Educação',
      image: '/dados/assim_que_acaba.jpg',
      preco: 38.59,
      contagem: 10,
      nota: 3.9,
      avaliacoes: 12,
      autor: 'Colleen Hoover',
    },
    {
      name: 'Hamlet',
      slug: 'livro-hamlet',
      categoria: 'Dramaturgia',
      image: '/dados/hamlet.jpg',
      preco: 9.45,
      contagem: 10,
      nota: 3.8,
      avaliacoes: 6,
      autor: 'William Shakespeare',
    },
    {
    name: 'A Biblioteca da Meia Noite',
    slug: 'livro-biblioteca',
    categoria: 'Romance',
    image: '/dados/biblioteca_meianoite.jpeg',
    preco: 37.42,
    contagem: 10,
    nota: 3.8,
    avaliacoes: 9,
    autor: 'Matt Haig',
  },
  {
    name: 'A Revolução dos Bichos',
    slug: 'livro-revolucao',
    categoria: 'Classicos',
    image: '/dados/revolucao.jpeg',
    preco: 10.95,
    contagem: 10,
    nota: 4.8,
    avaliacoes: 20,
    autor: 'Matt Haig',
  },
  {
    name: 'Torto Arado',
    slug: 'livro-torto',
    categoria: 'Educacao',
    image: '/dados/torto.jpeg',
    preco: 39.99,
    contagem: 5,
    nota: 4.8,
    avaliacoes: 11,
    autor: 'Itamar Franco',
  },
  {
    name: 'Em busca de mim',
    slug: 'livro-viola',
    categoria: 'Biografia',
    image: '/dados/viola.jpeg',
    preco: 29.49,
    contagem: 11,
    nota: 4.2,
    avaliacoes: 7,
    autor: 'Viola Davis',
  },
  {
    name: 'A vida não é útil',
    slug: 'livro-vida',
    categoria: 'Educacao',
    image: '/dados/avida.jpeg',
    preco: 26.99,
    contagem: 8,
    nota: 4.8,
    avaliacoes: 5,
    autor: 'Ailton Krenak',
  },
  {
    name: 'A jornada da humanidade',
    slug: 'livro-jornada',
    categoria: 'Educacao',
    image: '/dados/jornada.jpeg',
    preco: 55.92,
    contagem: 15,
    nota: 4.4,
    avaliacoes: 15,
    autor: 'Oded Galor',
  },
  {
    name: 'A construção da maldade',
    slug: 'livro-construcao',
    categoria: 'Educacao',
    image: '/dados/aconstrucao.jpeg',
    preco: 37.99,
    contagem: 15,
    nota: 4.0,
    avaliacoes: 12,
    autor: 'Roberto Motta',
  },
  {
    name: 'Daisy Jones and The Six',
    slug: 'livro-daisy',
    categoria: 'Romance',
    image: '/dados/daisy.jpeg',
    preco: 29.95,
    contagem: 14,
    nota: 4.6,
    avaliacoes: 4,
    autor: 'Taylor Jenkins',
  },
  {
    name: 'A vida invisível de Addie LaRue',
    slug: 'livro-vida',
    categoria: 'Romance',
    image: '/dados/vida_invisivel.jpeg',
    preco: 32.99,
    contagem: 10,
    nota: 4.0,
    avaliacoes: 9,
    autor: 'VE Schwab',
  },
  {
    name: 'Racionais: Sobrevivendo no Inferno',
    slug: 'livro-racionais',
    categoria: 'Musical',
    image: '/dados/racionais.jpeg',
    preco: 27.99,
    contagem: 13,
    nota: 4.8,
    avaliacoes: 21,
    autor: 'Racionais MCs',
  },
  {
    name: 'Meu pé de laranja lima',
    slug: 'livro-meupe',
    categoria: 'Romance',
    image: '/dados/meupe.jpeg',
    preco: 24.99,
    contagem: 11,
    nota: 4.9,
    avaliacoes: 10,
    autor: 'José Vasconcelos',
  }

  ],
};

/* exportar os dados para outros repositórios */
export default data;
